### ISSUE TITLE
dSQ doesn't parse --requeue option properly

### ISSUE THREAD

**Issue by tlangfor** [ycrc/dSQ#1]
Since the `--requeue` option doesn't have a second argument, dSQ doesn't parse it properly. For people who want to use scavenge queues, this would be super helpful.

**Comment by brevans** [comment]
Think we need to just have `argparse` handle the arguments in two passes. Started to think about this then got distracted. I'll try to find the example that inspired me

**Comment by tlangfor** [comment]
I was able to trick it by using `--requeue \ `, but it's a bit hacky...

**Comment by kayleanelson** [comment]
Works:
```
$ dSQ --jobfile jobfile.txt --cpus-per-task=2
#!/bin/bash

#SBATCH --array=0-2
#SBATCH --job-name=jobfile.txt
#SBATCH --cpus-per-task=2
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kaylea.nelson@yale.edu
#SBATCH --ntasks=1

/apps/hpc.rhel7/Tools/dSQ/dSQBatch.py jobfile.txt
```

Broken:
```
$ dSQ --jobfile jobfile.txt --cpus-per-task=2 --requeue
Error parsing arguments
```
