### ISSUE TITLE
Does dSQ need to be able to submit jobs from a compute node?

### ISSUE THREAD

**Issue by davidecarlson** [ycrc/dSQ#16]
Hi there,
I'm interested in potentially using dSQ for my work, but just from looking at the documentation, it appears that dSQ needs to be able to submit new jobs from a compute node.  Is that correct?  
The cluster that I do work on currently only allows jobs to be submitted from the login nodes, so I just wanted to double check.
Thanks!
Dave

**Comment by tlangfor** [comment]
Hi Dave, we have no issues launching dSQ jobs from the login nodes. It creates a standard Slurm sbatch script so there should be nothing wrong with using it from anywhere you can submit jobs.
