### ISSUE TITLE
Add option for limiting number of jobs running at once

### ISSUE THREAD

**Issue by tlangfor** [ycrc/dSQ#17]
Slurm provides a way to meter or limit the number of concurrently running jobs like this:

`--array=0-100%10`

which will only let 10 jobs run at the same time. 

There are some workflows that tend to be IO heavy and could benefit from being able to add a `--limit=10` or similar command-line option.

**Comment by brevans** [comment]
dSQ handles this with the `--max-jobs` option. Maybe it should be named better?

**Comment by tlangfor** [comment]
🤦
