### ISSUE TITLE
dSQ.py crashes when not called within a terminal

### ISSUE THREAD

**Issue by kenibrewer** [ycrc/dSQ#3]
When dsQ.py is not called within a live terminal it crashes with the following error message. 

> ```
> Traceback (most recent call last):
>   File "/ysm-gpfs/apps/software/dSQ/0.94/dSQ.py", line 15, in <module>
>     term_rows, term_columns = [int(x) for x in check_output(["stty", "size"]).split()]
>   File "/usr/lib64/python2.7/subprocess.py", line 575, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> subprocess.CalledProcessError: Command '['stty', 'size']' returned non-zero exit status 1
> ```

This crashes code I've written for use on Farnam that starts a job array dependent on completion of another job array. I can provide the specific code if necessary, but I imagine any task job array that is launched upon completion of another job array will face similar issues.

**Comment by brevans** [comment]
Hi Ken,

Would you mind downloading [this commit (76ef80a)](https://github.com/ycrc/dSQ/archive/76ef80a2cb5949f3d8730539c9407676895a29f3.zip) and see if that fixes things for your use case? If so I'll push it out to the clusters.

**Comment by kenibrewer** [comment]
@brevans It looks like you left out a semi-colon after except statement. You also need to import CalledProcessError from subprocess. 

With those additional changes it seems to mostly work, although there is still some error messages that get printed to the terminal that maybe should be suppressed. 

Here's is a test script file that should allow you to replicate the results on your end when submitted using sbatch.

```
#!/bin/bash

#SBATCH --partition=general
#SBATCH --job-name=test_dsq
#SBATCH --ntasks=1 --nodes=1
#SBATCH --mail-type=ALL

python ./dSQ.py 
```

**Comment by kenibrewer** [comment]
I would have submitted a pull request with my changes, but github seems to be having some server problems with the forking process.

**Comment by brevans** [comment]
Thanks Ken. Not my proudest commit, just wanted to get something out the door before the weekend. I'll have something better for you soon.
