### ISSUE TITLE
Add option to specify location of job_{}_status.tsv

### ISSUE THREAD

**Issue by kenibrewer** [ycrc/dSQ#4]
I would appreciate it if an option could be added to specify the location of where dSQ saves the job_{}_status.tsv file. 

I'm working with some legacy code that needs to be started from a particular directory. Having job_{}_status.tsv automatically be saved in the $PWD will result in a very cluttered main directory.

**Comment by brevans** [comment]
Ken - 

I plan on having an option for this implemented by day's end. After that I'll probably version bump and push out to YCRC clusters.
